export enum NotificationType {
  POST_LIKED = 'POST_LIKED',
  POST_COMMENTED = 'POST_COMMENTED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',

  USER_FOLLOWED = 'USER_FOLLOWED',
  USER_MENTIONED = 'USER_MENTIONED',

  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_REPLIED = 'MESSAGE_REPLIED',

  GROUP_ADDED = 'GROUP_ADDED',
  GROUP_INVITE_PENDING = 'GROUP_INVITE_PENDING',
}
