export const mockGames = [
  {
    id: "wuwa",
    slug: "wuthering-waves",
    name: "Wuthering Waves",
    description: "A community for Rovers to share builds, theories, lore and everything Wuthering Waves.",
    iconUrl: null,
    bannerUrl: null,
    developer: "Kuro Games",
    publisher: "Kuro Games",
    status: "ACTIVE",
    memberCount: 32100,
    postCount: 842,
  },
  {
    id: "hsr",
    slug: "honkai-star-rail",
    name: "Honkai: Star Rail",
    description: "Trailblazer discussions, team comps, relic farming, and story theories.",
    iconUrl: null,
    bannerUrl: null,
    developer: "HoYoverse",
    publisher: "HoYoverse",
    status: "ACTIVE",
    memberCount: 28700,
    postCount: 691,
  },
  {
    id: "genshin",
    slug: "genshin-impact",
    name: "Genshin Impact",
    description: "Character builds, exploration guides, Spiral Abyss teams, and region lore.",
    iconUrl: null,
    bannerUrl: null,
    developer: "HoYoverse",
    publisher: "HoYoverse",
    status: "ACTIVE",
    memberCount: 164200,
    postCount: 3210,
  },
  {
    id: "zzz",
    slug: "zenless-zone-zero",
    name: "Zenless Zone Zero",
    description: "Agent guides, disc builds, Hollow Zero strategy, and event chatter.",
    iconUrl: null,
    bannerUrl: null,
    developer: "HoYoverse",
    publisher: "HoYoverse",
    status: "ACTIVE",
    memberCount: 18700,
    postCount: 423,
  },
  {
    id: "pgr",
    slug: "punishing-gray-raven",
    name: "Punishing: Gray Raven",
    description: "Construct guides, team rotations, boss runs, and story archive threads.",
    iconUrl: null,
    bannerUrl: null,
    developer: "Kuro Games",
    publisher: "Kuro Games",
    status: "ACTIVE",
    memberCount: 9300,
    postCount: 207,
  },
];

export const mockCategories = [
  { id: "overview", name: "Overview", slug: "overview", isActive: true, sortOrder: 0 },
  { id: "builds", name: "Builds", slug: "builds", isActive: true, sortOrder: 1 },
  { id: "teams", name: "Teams", slug: "teams", isActive: true, sortOrder: 2 },
  { id: "lore", name: "Lore", slug: "lore", isActive: true, sortOrder: 3 },
  { id: "guides", name: "Guides", slug: "guides", isActive: true, sortOrder: 4 },
  { id: "events", name: "Events", slug: "events", isActive: true, sortOrder: 5 },
  { id: "media", name: "Media", slug: "media", isActive: true, sortOrder: 6 },
];

export const posts = [
  {
    id: "post-wuwa-hidden-quest",
    gameSlug: "wuthering-waves",
    title: 'Wuthering Waves 2.2 Hidden Quest "Tide of the Past" Guide',
    author: "RoverTide",
    time: "5h ago",
    tag: "Guide",
  },
  {
    id: "post-lament-theory",
    gameSlug: "wuthering-waves",
    title: "The Truth Behind the Lament - Lore Deep Dive",
    author: "LoreSeeker",
    time: "8h ago",
    tag: "Lore",
  },
  {
    id: "post-sanhua-build",
    gameSlug: "wuthering-waves",
    title: "Sanhua Main DPS Build Results - Patch 2.2",
    author: "SnowFrost",
    time: "12h ago",
    tag: "Build",
  },
  {
    id: "post-hsr-team",
    gameSlug: "honkai-star-rail",
    title: "Best Pure Fiction teams for low-investment accounts",
    author: "RailArchivist",
    time: "1d ago",
    tag: "Teams",
  },
];
